version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=product-api-test
      - DB_USERNAME=root
      - DB_PASSWORD=

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: product-api-test
    volumes:
      - db_data:/var/lib/mysql

  tests:
    build:
      context: .
    container_name: tests
    depends_on:
      - app
      - db
    command: ["php", "artisan", "test"]
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=your_database
      - DB_USERNAME=root
      - DB_PASSWORD=your_password

volumes:
  db_data:
